version: '3.7'

services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    restart: unless-stopped
    networks:
      - private

  faye:
    build: .
    links:
      - redis
    depends_on:
      - redis
    ports:
      - 4242:4242
      - 4443:4443
    env_file:
      - ./faye/.env
    volumes:
      - ./ssl:/etc/ssl/certs/faye
    networks:
      - public
      - private

networks:
  public:
  private: