version: '3.7'

services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    restart: unless-stopped
    networks:
      - private

  nginx:
    build: 
      context: .
      dockerfile: nginx.Dockerfile
    links:
      - faye
    depends_on:
      - faye
    ports:
      - 8080:80
      - 8443:443
    env_file:
      ./nginx/.env
    volumes:
      - ./ssl:/opt/ssl
    networks:
      - public
      - private

  faye:
    build: 
      context: .
      dockerfile: faye.Dockerfile
    links:
      - redis
    depends_on:
      - redis
    expose:
      - 4242
    env_file:
      - ./faye/.env
    volumes:
      - ./tokens:/usr/local/faye/tokens
    networks:
      - private

networks:
  public:
  private: